services:
  tvnow-mysql:
    image: mysql:8.0.40
    container_name: tvnow-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - tvnow-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - tvnow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 5
      timeout: 10s
      start_period: 20s

  tvnow-redis:
    image: redis:latest
    container_name: tvnow-redis
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: redis
    volumes:
      - tvnow-redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - tvnow-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 5
      timeout: 5s
      start_period: 10s

  tvnow-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tvnow-api
    container_name: tvnow-api
    working_dir: /var/www/
    ports:
      - "8080:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - tvnow-mysql
      - tvnow-redis
    networks:
      - tvnow-network
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379

  tvnow-nginx:
    image: nginx:alpine
    container_name: tvnow-nginx
    ports:
      - "5901:80"
      - "5904:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - tvnow-api
    networks:
      - tvnow-network

  tvnow-worker:
    container_name: tvnow-worker
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/var/www
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - tvnow-mysql
      - tvnow-redis
    networks:
      - tvnow-network
    healthcheck:
      test: ["CMD", "celery", "-A", "app.core.celery_app", "status"]
      retries: 5
      timeout: 10s
      start_period: 30s

  tvnow-flower:
    container_name: tvnow-flower
    build: .
    command: celery -A app.core.celery_app flower --port=5555
    volumes:
      - .:/var/www
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - tvnow-mysql
      - tvnow-redis
      - tvnow-worker
    networks:
      - tvnow-network
  
  tvnow-celery-beat:
    container_name: tvnow-celery-beat
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    volumes:
      - .:/var/www
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - tvnow-mysql
      - tvnow-redis
      - tvnow-worker
    networks:
      - tvnow-network

networks:
  tvnow-network:
    driver: bridge

volumes:
  tvnow-mysql-data:
    driver: local
  tvnow-redis-data:
    driver: local
